# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: chown
        name: chown $USER
        entry: bash -c "sudo chown -R $USER:$USER ."
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.*\.(tftpl|css|map|js)$'
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: bash -c "yamllint ."
        language: system
