version: '3.9'

networks:
  local:

services:
  app:
    build: .
    networks:
      - local
    volumes:
      - ${PWD}:/work
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    working_dir: /work

  mkdocs:
    image: squidfunk/mkdocs-material:latest
    network_mode: host
    volumes:
      - ${PWD}:/docs
    working_dir: /docs
